"use client";

import { useSearchParams } from "next/navigation";
import { Suspense } from "react";
import { CheckCircle2, MessageCircle, Clock, Star } from "lucide-react";

const WHATSAPP_NUMBER = "919999999999";

function ThankYouContent() {
  const params = useSearchParams();
  const paymentId = params.get("payment_id");
  const name = params.get("name") ?? "";

  const whatsappMsg = encodeURIComponent(
    `Hello Rekha ji, I have completed my payment for the Chaldean Numerology Report.${name ? ` My name is ${name}.` : ""} Payment ID: ${paymentId ?? "N/A"}. Please send my report. 🙏`
  );

  return (
    <main
      style={{ background: "var(--bg)", minHeight: "100vh" }}
      className="flex flex-col items-center justify-center px-6 py-16"
    >
      {/* Glow backdrop */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            "radial-gradient(ellipse 50% 50% at 50% 40%, rgba(61,240,90,0.08) 0%, transparent 70%)",
        }}
      />

      <div className="relative z-10 max-w-lg w-full text-center">
        {/* Success icon */}
        <div
          className="w-24 h-24 rounded-full flex items-center justify-center mx-auto mb-8"
          style={{
            background: "rgba(61,240,90,0.12)",
            border: "2px solid rgba(61,240,90,0.4)",
            boxShadow: "0 0 40px rgba(61,240,90,0.2)",
          }}
        >
          <CheckCircle2 size={44} style={{ color: "#3df05a" }} />
        </div>

        {/* Heading */}
        <h1
          className="text-4xl font-black mb-3"
          style={{ fontFamily: "var(--font-cinzel)", color: "#fff" }}
        >
          Payment Successful!
        </h1>
        {name && (
          <p className="text-lg mb-2" style={{ color: "#3df05a" }}>
            Thank you, {name}! 🙏
          </p>
        )}
        <p className="text-sm mb-8" style={{ color: "#9ca3af" }}>
          Your Chaldean Numerology Report is being prepared by Rekha ji personally.
        </p>

        {/* Payment ID */}
        {paymentId && (
          <div
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full mb-8 text-xs font-mono"
            style={{
              background: "rgba(61,240,90,0.08)",
              border: "1px solid rgba(61,240,90,0.2)",
              color: "#6b7280",
            }}
          >
            Payment ID: <span style={{ color: "#9ca3af" }}>{paymentId}</span>
          </div>
        )}

        {/* What happens next */}
        <div
          className="rounded-2xl p-6 mb-8 text-left"
          style={{
            background: "linear-gradient(135deg, #0d0d11, #111117)",
            border: "1px solid rgba(61,240,90,0.15)",
          }}
        >
          <h2 className="text-sm font-bold mb-4" style={{ color: "#fff", letterSpacing: "0.05em" }}>
            What happens next?
          </h2>
          <ul className="space-y-4">
            {[
              {
                icon: <Clock size={16} style={{ color: "#3df05a" }} />,
                title: "Report Generation",
                desc: "Your personalised report is being generated by our AI and reviewed by Rekha ji.",
              },
              {
                icon: <MessageCircle size={16} style={{ color: "#3df05a" }} />,
                title: "WhatsApp Delivery",
                desc: "Your 30+ page PDF report will be sent to your WhatsApp within 24 hours.",
              },
              {
                icon: <Star size={16} style={{ color: "#3df05a" }} />,
                title: "Free Follow-Up",
                desc: "Rekha ji will personally follow up to answer any questions about your report.",
              },
            ].map((step, i) => (
              <li key={i} className="flex items-start gap-3">
                <div
                  className="w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0"
                  style={{ background: "rgba(61,240,90,0.12)" }}
                >
                  {step.icon}
                </div>
                <div>
                  <p className="text-sm font-semibold text-white">{step.title}</p>
                  <p className="text-xs mt-0.5" style={{ color: "#6b7280" }}>{step.desc}</p>
                </div>
              </li>
            ))}
          </ul>
        </div>

        {/* WhatsApp CTA */}
        <a
          href={`https://wa.me/${WHATSAPP_NUMBER}?text=${whatsappMsg}`}
          target="_blank"
          rel="noopener noreferrer"
          className="btn-primary w-full py-4 rounded-xl text-base font-bold flex items-center justify-center gap-3 mb-4"
        >
          <MessageCircle size={20} />
          Confirm on WhatsApp
        </a>

        <a href="/" className="text-sm" style={{ color: "#6b7280" }}>
          ← Back to Home
        </a>
      </div>
    </main>
  );
}

export default function ThankYouPage() {
  return (
    <Suspense>
      <ThankYouContent />
    </Suspense>
  );
}
